param:
  general:
    project: m-sa
    service: m-sa-core-api
    language: dotnet
  cicd:
    sourcecode:
      url: https://xxxx/yyyy.git
      cred: GITLAB_CREDS
      branch:
        dev: dev
        sit: master
    stage_enable:
      dev:
        sonarqube: false
        checkmarx:  false
      sit:
        sonarqube: true
        checkmarx:  true
  artifact:
    url: https://ccc3:8443
    repo:
      dev: xx
      sit: yy
    cred: NEXUS_CREDS
  sonarqube:
    url: "https://192.168.22.22"
